# Generated by Django 4.1.3 on 2022-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('categoryId', models.IntegerField()),
                ('slug', models.TextField()),
                ('title', models.TextField()),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
