# Generated by Django 4.1.4 on 2022-12-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_users'),
        ('users', '0002_user_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='user',
            name='shifts',
            field=models.ManyToManyField(through='shifts.UserShift', to='shifts.shift'),
        ),
    ]
