# Generated by Django 4.1.4 on 2022-12-12 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='users',
            field=models.ManyToManyField(through='shifts.UserShift', to=settings.AUTH_USER_MODEL),
        ),
    ]
