# Generated by Django 4.1.4 on 2022-12-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='user',
            new_name='notifications_user_id',
        ),
    ]
